/** LaTeX snippets for toolbar and equation editor gallery. */

export const LATEX_GALLERY = [
  {
    id: 'frac-xy',
    label: 'Fraction',
    category: 'Basic',
    latex: '\\frac{x^2+y^2}{a+b}',
    display: true,
  },
  {
    id: 'int-exp',
    label: 'Integral',
    category: 'Calculus',
    latex: '\\int_0^{\\infty} e^{-x}\\, dx',
    display: true,
  },
  {
    id: 'sum',
    label: 'Summation',
    category: 'Calculus',
    latex: '\\sum_{i=1}^{n} i^2',
    display: true,
  },
  {
    id: 'sqrt',
    label: 'Square root',
    category: 'Basic',
    latex: '\\sqrt{x^2+y^2}',
    display: true,
  },
  {
    id: 'matrix',
    label: 'Matrix',
    category: 'Linear algebra',
    latex: '\\begin{bmatrix}\n1 & 2 \\\\\n3 & 4\n\\end{bmatrix}',
    display: true,
  },
  {
    id: 'limit',
    label: 'Limit',
    category: 'Calculus',
    latex: '\\lim_{x \\to \\infty}\\left(1+\\frac{1}{x}\\right)^x',
    display: true,
  },
  {
    id: 'piecewise',
    label: 'Piecewise',
    category: 'Functions',
    latex:
      'f(x)=\\begin{cases}\nx^2 & x>0 \\\\\n0 & x=0 \\\\\n-x & x<0\n\\end{cases}',
    display: true,
  },
  {
    id: 'derivative',
    label: 'Derivative',
    category: 'Calculus',
    latex: '\\frac{d}{dx}\\left(x^2\\ln x\\right)',
    display: true,
  },
  {
    id: 'power',
    label: 'Power',
    category: 'Basic',
    latex: 'x^2',
    display: false,
  },
  {
    id: 'subscript',
    label: 'Subscript',
    category: 'Basic',
    latex: 'H_2O',
    display: false,
  },
]

/** Quick-insert toolbar actions (not full gallery). */
export const MATH_TOOLBAR_ACTIONS = [
  { id: 'sup', type: 'script', mode: 'sup', label: 'x²', title: 'Superscript — select text first' },
  { id: 'sub', type: 'script', mode: 'sub', label: 'H₂', title: 'Subscript — select text first' },
  {
    id: 'frac',
    type: 'snippet',
    label: 'a/b',
    title: 'Fraction',
    latex: '\\frac{}{}',
    display: false,
    cursorOffset: 6,
  },
  {
    id: 'sqrt',
    type: 'snippet',
    label: '√',
    title: 'Square root',
    latex: '\\sqrt{}',
    display: false,
    cursorOffset: 6,
  },
  {
    id: 'int',
    type: 'snippet',
    label: '∫',
    title: 'Integral',
    latex: '\\int_{}^{} ',
    display: false,
    cursorOffset: 5,
  },
  {
    id: 'iint',
    type: 'snippet',
    label: '∬',
    title: 'Double integral',
    latex: '\\iint_{}^{} ',
    display: false,
    cursorOffset: 6,
  },
  {
    id: 'sum',
    type: 'snippet',
    label: 'Σ',
    title: 'Summation',
    latex: '\\sum_{i=1}^{n} ',
    display: false,
    cursorOffset: 5,
  },
  {
    id: 'lim',
    type: 'snippet',
    label: 'lim',
    title: 'Limit',
    latex: '\\lim_{x \\to \\infty} ',
    display: false,
    cursorOffset: 5,
  },
  {
    id: 'matrix',
    type: 'snippet',
    label: '[]',
    title: 'Matrix',
    latex: '\\begin{bmatrix}\n1 & 2 \\\\\n3 & 4\n\\end{bmatrix}',
    display: true,
  },
  {
    id: 'cases',
    type: 'snippet',
    label: '{',
    title: 'Piecewise function',
    latex:
      '\\begin{cases}\n x^2 & x>0 \\\\\n 0 & x=0 \\\\\n -x & x<0\n\\end{cases}',
    display: true,
  },
  {
    id: 'deriv',
    type: 'snippet',
    label: 'd/dx',
    title: 'Derivative',
    latex: '\\frac{d}{dx}\\left(\\right)',
    display: true,
    cursorOffset: 15,
  },
  { id: 'latex', type: 'modal', label: 'LaTeX', title: 'Open equation editor' },
]
